const NUM_MAPPERS = 3;
const NUM_REDUCERS = 2;
const NUM_WORKERS = 5;
const MASTER_PORT = 3000;
const WORKER_PORTS = [3001, 3002, 3003, 3004, 3005];
const FILE_PARTS_DIR = "./file_parts";
const MAPPER_FILE_PATH = "./public/mapper.js";
const REDUCER_FILE_PATH = "./public/reducer.js";
const INPUT_FILE_PATH = "./public/input.txt";
const OUTPUT_FILES = [];
for (let i = 0; i < NUM_REDUCERS; i++) {
  OUTPUT_FILES.push(`output-reducer-${i}.json`);
}
const MAP_PORTS = WORKER_PORTS.slice(0, NUM_MAPPERS);
const REDUCE_PORTS = WORKER_PORTS.slice(
  NUM_MAPPERS,
  NUM_MAPPERS + NUM_REDUCERS
);
const BASE_URL = "http://localhost";
const STATES = {
  WORKER_IDLE: "WORKER_IDLE",
  WORKER_RUNNING: "WORKER_RUNNING",
  WORKER_ERROR: "WORKER_ERROR",
  REDUCE_PHASE: "REDUCE_PHASE",
  MAP_PHASE: "MAP_PHASE",
  MAP_RUNNING: "MAP_RUNNING",
  MAP_ERROR: "MAP_ERROR",
  MAP_COMPLETED: "MAP_COMPLETED",
  REDUCE_RUNNING: "REDUCE_RUNNING",
  REDUCE_ERROR: "REDUCE_ERROR",
  REDUCE_COMPLETED: "REDUCE_COMPLETED",
};

module.exports = {
  NUM_MAPPERS,
  NUM_REDUCERS,
  NUM_WORKERS,
  MASTER_PORT,
  WORKER_PORTS,
  FILE_PARTS_DIR,
  MAPPER_FILE_PATH,
  REDUCER_FILE_PATH,
  INPUT_FILE_PATH,
  MAP_PORTS,
  REDUCE_PORTS,
  BASE_URL,
  STATES,
  OUTPUT_FILES,
};
